// <auto-generated />
namespace Truck.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview7-19363-02")]
    public sealed partial class TruckInspection_V3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TruckInspection_V3));
        
        string IMigrationMetadata.Id
        {
            get { return "201908041731451_TruckInspection_V3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
